'use strict'

export const USER_SET = 'USER_SET'
export const AUTH_CHECKED = 'AUTH_CHECKED'
export const TEMPLATES_SET = 'TEMPLATES_SET'
export const LICENSE_VERIFIED = 'LICENSE_VERIFIED'

export const COLLAGES_SET = 'COLLAGES_SET'
export const CURRENT_COLLAGE_SET = 'CURRENT_COLLAGE_SET'
export const COLLAGE_UPDATED = 'COLLAGE_UPDATED'

export const NOTIFICATION_SET = 'NOTIFICATION_SET'
export const NOTIFICATIONS_SET = 'NOTIFICATIONS_SET'
export const NOTIFICATIONS_LOADING_SET = 'NOTIFICATIONS_LOADING_SET'

export const CATEGORIES_SET = 'CATEGORIES_SET'
export const CURRENT_CATEGORY_SET = 'CURRENT_CATEGORY_SET'

export const SEARCH_CLEARED = 'SEARCH_CLEARED'
export const SEARCH_SUGGESTING_SET = 'SEARCH_SUGGESTING_SET'
export const SEARCH_SET = 'SEARCH_SET'

export const ENTITIES_SET = 'ENTITIES_SET'
export const ENTITY_SET = 'ENTITY_SET'

export const LIST_IS_LOADING_SET = 'LIST_IS_LOADING_SET'
export const LIST_IS_SEARCHING_SET = 'LIST_IS_SEARCHING_SET'

export const AUTOSAVE_STATUS_SET = 'AUTOSAVE_STATUS_SET'
export const AUTOSAVE_TIMER_SET = 'AUTOSAVE_TIMER_SET'

export const CURRENT_UPLOAD_SET = 'CURRENT_UPLOAD_SET'
export const CURRENT_UPLOAD_ADDED = 'CURRENT_UPLOAD_ADDED'

export const UNDO_STACK_SIZE_SET = 'UNDO_STACK_SIZE_SET'
export const REDO_STACK_SIZE_SET = 'REDO_STACK_SIZE_SET'

export const CURRENT_MODEL_SET = 'CURRENT_MODEL_SET'
export const CURRENT_MODEL_CHANGING_SET = 'CURRENT_MODEL_CHANGING_SET'

export const ERRORS_SET = 'ERRORS_SET'
export const STAGE_SET = 'STAGE_SET'
export const RIGHT_PANEL_SHOWN = 'RIGHT_PANEL_SHOWN'
export const LEFT_PANEL_SET = 'LEFT_PANEL_SET'
export const COLOR_PICKER_INIT_COLOR_SET = 'COLOR_PICKER_INIT_COLOR_SET'
export const ARTBOARD_SET = 'ARTBOARD_SET'
export const BACKDROP_SHOWN_SET = 'BACKDROP_SHOWN_SET'
export const IS_MOBILE_SET = 'IS_MOBILE_SET'
export const CLEAR = 'CLEAR'
